# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b82e99c11684442061ace002fda3035ef34ca40cf00c9bfc469efc80dd592358cdf0a82f1900347d40ac4b3fe3f5cce9c0fb3a6f1a16cc7914b26e9c1135241

test:
  secret_key_base: 14efeb6a1cfc5215346cb3c6991a94390d5cc01ea37202de195749ccecf2adc8f874bc3cba2cdac8b78929297f32e8ace9d8b166c351ad29673b55df6ea8c7d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
